### ISSUE TITLE
Options from same section should be stored as a single option in the db

### ISSUE THREAD

**Issue by richardtape** [NateWr/simple-admin-pages#3]
Title says it all really, but doing this prevents multiple calls to the database to retrieve more than one option. It's a generally accepted practice within WP.

**Comment by timiwahalahti** [comment]
Hi Nate, thanks for this amazing library!

I'm re-opening this issue because i think that there should be (at least) option to save settings as a single for each section, not for each page. I think that would make data structure simpler in most cases.

Example: I have page with three sections for different use cases (eg contact page, front page and footer) and each section has let's say 5-15 fields. I'm forced to get all those settings in situation where i need only one section. Also the naming would be more logical, because now the settings are not saved in multidimensional arrays. Section id's does not have any effect, now field id's needs to be prefixed with it to recognize field's correctly.

**Comment by NateWr** [comment]
Hi @timiwahalahti. This sounds like a nice feature. I've opened up a separate issue with a bit of detail: https://github.com/NateWr/simple-admin-pages/issues/10

I usually add features when and as I need them. So I may not add support for this any time soon. But I'm always open to PRs.
